# terraform-docs configuration file
# See https://terraform-docs.io/user-guide/configuration/ for all options

formatter: markdown table
output:
  file: README.md
  mode: inject
  template: |
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
sections:
  hide:
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs
    - examples
    - header
    - footer
    - dependencies
