name: 'Send Deployment Notification'
description: 'Send email notification about deployment status'
inputs:
  type:
    description: 'Notification type: success or failure'
    required: true
  recipient:
    description: 'Email recipient'
    required: true
  deployment_id:
    description: 'Deployment ID'
    required: true
  resource_type:
    description: 'Resource type'
    required: true
  environment:
    description: 'Environment'
    required: true
  subscription:
    description: 'Azure subscription'
    required: true
  outputs:
    description: 'Terraform outputs'
    required: false
  error_message:
    description: 'Error message for failures'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Generate HTML Report
      shell: bash
      run: |
        mkdir -p /tmp/reports
        cat > /tmp/reports/deployment-report.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Deployment Report - ${{ inputs.deployment_id }}</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .header { background-color: #f8f9fa; padding: 20px; border-radius: 5px; }
                .success { color: #28a745; }
                .failure { color: #dc3545; }
                .details { margin: 20px 0; }
                .outputs { background-color: #f8f9fa; padding: 15px; border-radius: 5px; }
                pre { background-color: #f1f1f1; padding: 10px; border-radius: 3px; overflow-x: auto; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1 class="${{ inputs.type }}">
                    ${{ inputs.type == 'success' && '✅ Deployment Successful' || '❌ Deployment Failed' }}
                </h1>
            </div>
            
            <div class="details">
                <h2>Deployment Details</h2>
                <table>
                    <tr><td><strong>Deployment ID:</strong></td><td>${{ inputs.deployment_id }}</td></tr>
                    <tr><td><strong>Resource Type:</strong></td><td>${{ inputs.resource_type }}</td></tr>
                    <tr><td><strong>Environment:</strong></td><td>${{ inputs.environment }}</td></tr>
                    <tr><td><strong>Subscription:</strong></td><td>${{ inputs.subscription }}</td></tr>
                    <tr><td><strong>Deployed At:</strong></td><td>$(date -u +"%Y-%m-%d %H:%M:%S UTC")</td></tr>
                </table>
            </div>

            ${{ inputs.type == 'success' && format('<div class="outputs"><h2>Resource Outputs</h2><pre>{0}</pre></div>', inputs.outputs) || format('<div class="outputs"><h2>Error Details</h2><pre>{0}</pre></div>', inputs.error_message) }}

            <div class="details">
                <h2>Next Steps</h2>
                ${{ inputs.type == 'success' && '<p>Your resources have been successfully deployed and are ready for use. You can access them through the Azure portal using the subscription and resource group specified above.</p>' || '<p>The deployment encountered an error. Please review the error details above and contact the infrastructure team if you need assistance resolving the issue.</p>' }}
            </div>

            <hr>
            <p><small>Generated by Erdtree Self-Service Portal | <a href="https://github.com/your-org/erdtree-infrastructure">View on GitHub</a></small></p>
        </body>
        </html>
        EOF

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: '${{ inputs.type == ''success'' && ''✅'' || ''❌'' }} Erdtree Deployment ${{ inputs.type == ''success'' && ''Complete'' || ''Failed'' }} - ${{ inputs.resource_type }}'
        to: ${{ inputs.recipient }}
        cc: hemirafl@microsoft.com
        from: erdtree-portal@microsoft.com
        html_body: file:///tmp/reports/deployment-report.html
        attachments: /tmp/reports/deployment-report.html
        priority: ${{ inputs.type == 'failure' && 'high' || 'normal' }}