name: Terraform CI/CD (Dev)

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  TERRAFORM_VERSION: 1.9.0
  GO_VERSION: 1.22
  TERRAFORM_DOCS_VERSION: v0.18.0

jobs:
  check:
    name: 0 Terraform Check (fmt, validate, plan) [Dev]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Select/Create Terraform Workspace (Dev)
        run: |
          terraform workspace select dev || terraform workspace new dev
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
      - name: Terraform Plan (Dev)
        run: terraform plan -var-file=dev.tfvars -out=tfplan.binary
      - name: Upload Plan File
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan.binary
  apply:
    name:  Terraform Apply [Dev]
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'workflow_dispatch'
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Select/Create Terraform Workspace (Dev)
        run: |
          terraform workspace select dev || terraform workspace new dev
      - name: Terraform Init
        run: terraform init -input=false
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
      - name: Terraform Apply (Dev)
        run: terraform apply -auto-approve tfplan.binary
